### ISSUE TITLE
接口地址无法打开

### ISSUE THREAD

**Issue by ZhaoQiubai** [Chinzicam/DevEcoStudioProjects#2]
你好，能获取以下你的接口里的文件内容吗

**Comment by Chinzicam** [comment]
这个项目是我学校里专业课老师布置的大作业，接口是老师那边提供的，课程结束后老师就把接口关了，我这边也没有源数据库。不过你可以具体参考接口文档和单机版MyApplication/entry/src/main/js/MainAbility/common/js路径下的接口格式自己写一个

**Comment by ZhaoQiubai** [comment]
好的，谢谢

橙子草 ***@***.***> 于2023年11月3日周五 17:09写道：
